### ISSUE TITLE
Can I use DepthShrinker to compress trained yolov5s model files

### ISSUE THREAD

**Issue by Nyove** [facebookresearch/DepthShrinker#2]
I want to compress my yolov5s model files. Do I just need to reformat my dataset?

**Comment by tilmto** [comment]
Hi, if you want to compress the backbone model in yolo5s from scratch, you may need to define your model in our format to enable the search for redundant activation functions, plus reformating the dataset and objectives. 

Note that our DepthShrinker targets compressing compact neural networks and inverted residual blocks are favored by DepthShrinker. This is because the channel numbers in a block are in a first-wide-then-narrow manner, which can maintain comparable or smaller FLOPs after merging, while for other types of blocks, the theoretical FLOPs may increase after merging due to the kernel size. Therefore, whether to use our DepthShrinker as a compression paradigm may depend on your target model structure.

**Comment by Nyove** [comment]
Thanks a lot for your reply. I'll make the decision considering my actual needs
