### ISSUE TITLE
I have puzzle after reading paper. Does DepthShrinker only work on MobileNetv2 based networks(the networks contains inverted residules)?

### ISSUE THREAD

**Issue by Nyove** [facebookresearch/DepthShrinker#3]

**Comment by tilmto** [comment]
Yes, our DepthShrinker targets compressing compact neural networks and inverted residual blocks are favored by DepthShrinker since the channel numbers in a block are in a first-wide-then-narrow manner, which can maintain comparable or smaller FLOPs after merging. For other types of blocks, the theoretical FLOPs may increase after merging due to the kernel size.

**Comment by Nyove** [comment]
Thanks a lot for your reply. I'll make the decision considering my actual needs
